name: Python Tests

on: [pull_request, push]

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      VENV: venv

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set Up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Set Up Virtual Environment
        run: |
          python3 -m venv $VENV
          source $VENV/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Tests
        run: |
          source $VENV/bin/activate
          pytest 